<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet" href="main.css">
  <title>Cotonnade & Co.</title>
</head>
<body>
  <header>
    <section class="group_logo">
      <h1 class="logo">Cotonnade & Co'</h1>
      <div class="back">
        <a href="" class="btn_back"><i class="fas fa-arrow-left"></i></a>
        <a href="" class="btn_new">Créer un compte</a>
      </div>
    </header>
    <main>
      <form action="" type="POST">
        <ul>
          <li>
            <h2>Connexion</h2>
          </li>
          <li>
            <label for="mail">E-mail</label>
            <input type="mail" id="mail" name="mail">
          </li>
          <li>
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password">
          </li>
          <li>
            <button type="submit">Se connecter</button>
          </li>
        </ul>
      </form>
    </main>
  </body>
</html>
