<main>
  <section class="description">
    <p>Cotonnade & Co. est une boutique en ligne de créations uniques conféctionnées par mes soins en France, à Oloron Sainte Marie (Pyrénées Atlantiques).</p>
    <p>Je privilégie les tissus européens de qualité, cértifiés Bio, Oeko tex ou Gots.</p>
    <p>Ici vous trouverez principalement des articles "Lifestyle" et "Zéro déchet".</p>
  </section>
  <?php foreach($categories as $category): ?>
    <section class="category">
      <h2><?= $category['title'] ?></h2>
      <div class="articles">
    <?php foreach($articles as $article): ?>
      <?php if($article['category_id'] == $category['id']): ?>
        <a class="level" href="article.php?id=<?= $article['id'] ?>">
          <img src="<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>">
          <h3><?= $article['price'] ?>€</h3>
        <?php if(isset($article['lots']) && !empty($article['lots'])): ?>
          <h3>/ lots de <?= $article['lots'] ?></h3>
        <?php endif; ?>
      </a>
  <?php endif; ?>
  <?php endforeach; ?>
    </div>
  </section>
<?php endforeach; ?>
</main>
<?php if(empty($_SESSION['cookie'])): ?>
  <div class="cookie" id="cookie">
    <p>Nous utilisons des cookies afin de concerver vos articles dans le panier pendant 15 jours,</p>
    <p>ainsi que pour l'option "Se souvenir de moi" lors de la connexion.</p>
    <button id="agree">D'accord</button>
    <button id="disagree">Non merci</button>
  </div>
  <script src="js/jquery-3.5.1.js"></script>
  <script src="js/cookie.js"></script>
<?php endif; ?>
