<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="../css/main.css">
  <link rel="stylesheet" href="css/main.css">
  <title>Valider la commande</title>
</head>
<body>
  <header class="header">
    <section class="group_logo">
      <h1 class="logo">Cotonnade & Co'</h1>
    </section>
    <section class="btn-group">
        <a href="../cart.php" class="btn_back">Annuler la commande</a>
    </section>
  </header>
  <main>
    <form class="order_form" action="ordering.php" method="post">
      <h2>Informations de livraison</h2>
      <ul>
        <li>
          <label for="email">Email :</label>
          <input type="email" name="email" value="<?= $user['email'] ?>" required />
        </li>
        <li>
          <label for="last_name">Nom :</label>
          <input type="text" name="last_name" value="<?= $user['last_name'] ?>" required />
        </li>
        <li>
          <label for="first_name">Prénom :</label>
          <input type="text" name="first_name" value="<?= $user['first_name'] ?>" required />
        </li>
        <li>
          <label for="postal_code">Code postale :</label>
          <input type="number" name="postal_code" value="<?= $postalCode ?>" required />
        </li>
        <li>
          <label for="city">Ville :</label>
          <input type="text" name="city" value="<?= $city ?>" required />
        </li>
        <li>
          <label for="adress">Adresse :</label>
          <input type="text" name="adress" value="<?= $adress ?>" required />
        </li>
      </ul>
      <section class="cart">
        <h2>Votre Commande :</h2>
        <ul>
          <?php foreach($articles as $article): ?>
            <li>
              <img class="edit_img" src="../<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>" />
              <div>
                <h3><?= $article['title'] ?></h3>
                <p>Quantité: <?= $article['quantity'] ?></p>
                <h4>Prix: <?= $article['price'] ?></h4>
              </div>
            </li>
          <?php endforeach; ?>
        </ul>
        <h3 class="total">Total: <?= $total ?> €</h3>
      </section>
      <button type="submit">Valider la commande</button>
    </form>
  </main>
</body>
</html>
