<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="../css/main.css">
  <link rel="stylesheet" href="css/main.css">
  <title>Paiement</title>
</head>
<body>
  <header class="header">
    <section class="group_logo">
      <h1 class="logo">Cotonnade & Co'</h1>
    </section>
    <section class="btn-group">
        <a href="../cart.php" class="btn_back">Annuler la commande</a>
    </section>
  </header>
  <main>
    <form class="order_form" action="success.php" method="post">
      <h2>Simulation de Paiement</h2>
      <ul>
        <li>
          <label for="name">Nom du titulaire de la carte :</label>
          <input type="text" name="name" required />
        </li>
        <li>
          <label for="card_code">Code de carte :</label>
          <input type="number" name="card_code" required />
        </li>
        <li>
          <label for="expiration_date">Date d'éxpiration :</label>
          <input type="text" name="expiration_date" required />
        </li>
        <li>
          <label for="crypto">Cryptogramme :</label>
          <input type="number" name="crypto" required />
        </li>
      </ul>
      <button type="submit">Procéder au paiement</button>
    </form>
  </main>
</body>
</html>
