<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Menu administrateur</title>
</head>
<body>
  <main>
    <a href="new.php">Créer un article</a>
    <a href="edit.php">Modifier des articles</a>
    <a href="delete.php">Supprimer des articles</a>
    <a href="stock.php">Géstion du stock</a>
    <a href="categories.php">Géstion des catégories</a>
    <a href="orders.php">Voir les commandes</a>
    <a class="logout" href="../connexion/logout.php">Déconnexion</a>
  </main>
</body>
</html>
