<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Gestion des catégories</title>
</head>
<body>
  <main>
    <form action="categories.php" method="post" class="cat_add">
      <h1>Ajouter une catégorie</h1>
      <div>
        <label for="title">Nom de la catégorie :</label>
        <input type="text" name="title" id="title" required />
      </div>
      <button type="submit">Créer la catégorie</button>
    </form>
    <section  class="cat_list">
      <ul class="ul">
        <?php foreach($categories as $category): ?>
          <li>
            <h2><?= $category['title'] ?></h2>
            <a class="cat_btn" href="categories.php?id=<?= $category['id'] ?>">Supprimer la catégorie</a>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  </main>
</body>
</html>
