<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Supprimer un article</title>
</head>
<body>
  <ul class="ul">
    <?php foreach($articles as $article): ?>
      <li class="li">
        <img class="delete_img" src="../<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>">
        <div class="delete_aside">
          <section class="delete_title">
            <h2><?= $article['title'] ?></h2>
            <section>
              <p>Price : <?= $article['price'] ?></p>
              <?php if(!empty($article['lots'])): ?>
                <p>/ lot de <?= $article['lots'] ?></p>
              <?php endif; ?>
            </section>
          </section>
          <a href="delete.php?id=<?= $article['id'] ?>">Supprimer l'article</a>
        </div>
      </li>
    <?php endforeach; ?>
  </ul>
</body>
</html>
