<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Modifier articles</title>
</head>
<body>
  <?php foreach($articles as $article): ?>
    <a class="edit_hover" href="editForm.php?id=<?= $article['id'] ?>">
      <img class="edit_img" src="../<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>" />
      <h2><?= $article['title'] ?></h2>
    </a>
  <?php endforeach; ?>
</body>
</html>
