<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Modifier articles</title>
</head>
<body>
  <form class="editForm" enctype="multipart/form-data" method="post" action="editForm.php">
    <ul>
      <li>
        <input type="hidden" name="id" value="<?= $article['id'] ?>" />
      </li>
      <li>
        <input class="editForm_title" type="text" id="title" name="title" value="<?= nl2br(htmlspecialchars($article['title'])) ?>" />
      </li>
      <li>
        <img id="preview" src="../<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>" />
        <input type="file" id="picture" name="picture" />
        <section>
          <label for="alt">Titre image :</label>
          <input type="text" id="alt" name="alt" value="<?= $article['alt'] ?>" />
        </section>
      </li>
      <li>
        <label for="price">Prix :</label>
        <input type="number" id="price" name="price" min="1" step="0.01" value="<?= $article['price'] ?>"/>
      </li>
      <li>
        <label for="lots">Par lot de (optionnel) :</label>
        <input type="number" id="lots" name="lots" min="1" value="<?= $article['lots'] ?>" />
      </li>
      <li>
        <label for="price">Description :</label>
        <textarea id="description" name="description" cols="50" rows="10"><?= nl2br(htmlspecialchars($article['description'])) ?></textarea>
      </li>
      <li>
        <label for="more_about">Détails :</label>
        <textarea id="more_about" name="more_about" cols="50" rows="10"><?= nl2br(htmlspecialchars($article['more_about'])) ?></textarea>
      </li>
      <li>
        <button type="submit">Modifier l'article</button>
      </li>
    </ul>
  </form>
  <script src="js/preview.js"></script>
</body>
</html>
