<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Créer un article</title>
</head>
<body>
  <form class="editForm" enctype="multipart/form-data" method="post" action="new.php">
    <ul>
      <li>
        <label for="title">Titre de l'article</label>
        <input class="editForm_title" type="text" id="title" name="title"/>
      </li>
      <li>
        <label for="picture">Image</label>
        <input type="file" id="picture" name="picture"/>
        <img src="../img/background/img-background.jpg" id="preview" alt="preview" />
        <section>
          <label for="alt">Nom d'image</label>
          <input type="text" id="alt" name="alt"/>
        </section>
      </li>
      <li>
        <label for="price">Prix</label>
        <input type="number" id="price" name="price" min="1" step="0.01"/>
      </li>
      <li>
        <label for="lots">par lots de (optionnel)</label>
        <input type="number" id="lots" name="lots" min="1" />
      </li>
      <li>
        <label for="description">Description générale</label>
        <textarea id="description" name="description" cols="50" rows="10"></textarea>
      </li>
      <li>
        <label for="more_about">En savoir plus</label>
        <textarea id="more_about" name="more_about" cols="50" rows="10"></textarea>
      </li>
      <li>
        <label for="stock">Stock</label>
        <input type="number" id="stock" name="stock" min="1" />
      </li>
      <li>
        <select id="category" name="category">
          <?php foreach($categories as $category): ?>
            <option value="<?= $category['id'] ?>"><?= $category["title"] ?></option>
         <?php endforeach; ?>
        </select>
      </li>
      <li>
        <button class="button button-primary" type="submit">Enregistrer</button>
      </li>
    </ul>
  </form>
  <script src="js/preview.js"></script>
</body>
</html>
