<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Commande</title>
</head>
<body>
  <main>
    <section class="info_order">
      <h1>Infos client :</h1>
      <p>Nom, Prénom : <?= $order['last_name']. ' ' .$order['first_name'] ?></p>
      <p>E-mail : <?= $order['email'] ?></p>
      <p>Adresse : <?= $order['adress'] ?></p>
      <p>Commandé le : <?= $order['ordered_at'] ?></p>
    </section>
    <section class="order_list">
      <h1>La commande :</h1>
        <ul class="ul">
          <?php foreach($cart as $article): ?>
            <li>
              <img src="../<?= $article['picture'] ?>" alt="<?= $article['alt'] ?>" />
              <div>
                <h2><?= $article['title'] ?></h2>
                <p>Quantité: <?= $article['quantity'] ?></p>
                <?php if(isset($article['lots']) && !empty($article['lots'])): ?>
                  <p>/ lots de <?= $article['lots'] ?></p>
                <?php endif; ?>
              </div>
            </li>
          <?php endforeach; ?>
        </ul>
    </section>
    <button class="order_btn" id="delete">Supprimer la commande</button>
    <div class="confirm hidden" id="confirm">
      <h2>Êtes-vous sûr(e) de vouloir supprimer cette commande ?</h2>
      <div>
        <form action="orders.php" method="post">
          <input type="hidden" value="<?= $order['id'] ?>" name="id" />
          <button id="yes" type="submit">Oui</button>
        </form>
        <button id="no">Non</button>
      </div>
    </div>
  </main>
<script src="../js/jquery-3.5.1.js"></script>
<script src="js/order.js"></script>
</body>
</html>
