<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/admin.css">
  <title>Commandes</title>
</head>
<body>
  <?php foreach($orders as $order): ?>
    <a class="edit_hover" href="orders.php?id=<?= $order['id'] ?>">
      <h2><?= $order['ordered_at'] ?></h2>
      <p>Mail client : <?= $order['email'] ?></p>
    </a>
  <?php endforeach; ?>
</body>
</html>
