<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet" href="../css/main.css">
  <title>Cotonnade & Co.</title>
</head>
<body>
  <header class="header">
    <section class="group_logo">
      <a class="logo" href="../index.php">Cotonnade & Co'</a>
    </section>
    <nav class="rs">
      <a href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a>
      <a href="https://www.instagram.com/?hl=fr"><i class="fab fa-instagram-square"></i></a>
      <a href="https://www.pinterest.fr/"><i class="fab fa-pinterest-square"></i></a>
    </nav>
    <section class="btn-group">
        <a href="login.php" class="btn_new">Se connecter</a>
    </section>
  </header>
  <main class="login_main">
    <form class="login_form" action="register.php" method="post">
      <ul>
        <li>
          <h2>Créer un compte</h2>
        </li>
        <li>
          <label for="email">E-mail :</label>
          <input type="email" id="email" name="email">
        </li>
        <li>
          <label for="last_name">Nom :</label>
          <input type="text" id="last_name" name="last_name">
        </li>
        <li>
          <label for="first_name">Prénom :</label>
          <input type="text" id="first_name" name="first_name">
        </li>
        <li>
          <label for="postal_code">Code postale :</label>
          <input type="number" id="postal_code" name="postal_code">
        </li>
        <li>
          <label for="city">Ville :</label>
          <input type="text" id="city" name="city">
        </li>
        <li>
          <label for="adress">Adresse :</label>
          <input type="text" id="adress" name="adress">
        </li>
        <li>
          <label for="password">Mot de passe :</label>
          <input type="password" id="password" name="password">
        </li>
        <li>
          <label for="confirm_password">Confirmer le mot de passe :</label>
          <input type="password" id="confirm_password" name="confirm_password">
        </li>
        <li>
          <button type="submit">Enregistrer</button>
        </li>
      </ul>
    </form>
  </main>
  </body>
</html>
